### ISSUE TITLE
Would you recommend this hardware combination?

### ISSUE THREAD

**Issue by dhcmega** [git-coder988/Ryzen-Hackintosh#4]
Hi
I'm planning on buying a Gigabyte B450 Aorus m and a Ryzen 5 3600
I already have a RX570.
Is sleeping working ok? Any important drawback?
Maybe the Gigabyte B450 DS3H it's easier to configure?
Thanks for sharing!

**Comment by git-coder988** [comment]
This config was made using the B450 Aorus M.  Sleep is working fine with this Github config.  Should be minimal mods to get you up and running...serial #, ROM, etc.  

You're on your own if you get a B450 DS3H.  I don't own one nor have I tested with one.
